Update upgrade to support autoscaler
- Add 1.17 support
- hold k8s packages to stop them being upgraded accidentally
- streamline node upgrade code in line with recommendations

diff --git a/master/templates/install-master b/master/templates/install-master
--- a/master/templates/install-master
+++ b/master/templates/install-master
@@ -2,6 +2,7 @@
 
 set -e
 
+
 install_cert() {
         local source_prefix=$${1}
         local dest_prefix=$${2:-$${1}}
@@ -366,15 +367,27 @@ upgrade() {
         #sudo systemctl restart docker
         echo "Kubeadm installed master detected - checking for upgrade"
         sudo apt-get -qq update -y
-        sudo apt-get -qq install debconf-utils
+        sudo apt-get -qq install -y  debconf-utils
         echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
-        sudo apt-get -qq install kubeadm=${kubernetes_release}-00
+	sudo apt-mark unhold kubeadm
+        if ! sudo apt-get -qq install -y kubeadm=${kubernetes_release}-00
+	then
+		sudo apt-mark hold kubeadm
+		echo "Failed to install kubeadm at version ${kubernetes_release}-00"
+		echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
+		return 2
+	fi
+	sudo apt-mark hold kubeadm
         if sudo kubeadm upgrade plan --config $HOME/install/kubeadm.conf | egrep -q '^\s*kubeadm upgrade apply'
         then
                 retry 5 sudo kubeadm upgrade apply -y --config $HOME/install/kubeadm.conf
-                sudo apt-get -qq install \
-                        kubectl=${kubernetes_release}-00 \
-                        kubelet=${kubernetes_release}-00
+		echo "Upgrading kubelet"
+		sudo apt-mark unhold kubelet kubectl
+		retry 5 sudo apt-get -qq -y install \
+			kubectl=${kubernetes_release}-00 \
+			kubelet=${kubernetes_release}-00
+		sudo apt-mark hold kubelet kubectl
+		retry 5 sudo systemctl restart kubelet
         else
                 echo "Already at version ${kubernetes_release} or greater - skipping"
         fi
diff --git a/master/templates/install-master-mirror b/master/templates/install-master-mirror
--- a/master/templates/install-master-mirror
+++ b/master/templates/install-master-mirror
@@ -186,17 +186,26 @@ upgrade() {
         echo "Kubeadm installed master detected - checking for upgrade"
         sudo apt-get -qq update -y
         sudo apt-get -qq install debconf-utils
-        echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
-        sudo apt-get -qq install kubeadm=${kubernetes_release}-00
-        if sudo kubeadm upgrade plan --config $HOME/install/kubeadm.conf | egrep '^\s*kubeadm upgrade apply'
-        then
-                retry 5 sudo kubeadm upgrade apply -y --config $HOME/install/kubeadm.conf
-                sudo apt-get -qq install \
-                        kubectl=${kubernetes_release}-00 \
-                        kubelet=${kubernetes_release}-00
-        else
-                echo "Already at version ${kubernetes_release} or greater - skipping"
-        fi
+	echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
+	echo "Upgrading kubeadm"
+	sudo apt-mark unhold kubeadm
+	if ! sudo apt-get -qq -y install kubeadm=${kubernetes_release}-00
+	then
+		sudo apt-mark hold kubeadm
+		echo "Failed to install kubeadm at version ${kubernetes_release}-00"
+		echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
+		exit 2
+	fi
+	sudo apt-mark hold kubeadm
+	echo "Upgrading control plane mirror"
+	retry 5 sudo kubeadm upgrade node
+	echo "Upgrading kubelet"
+	sudo apt-mark unhold kubelet kubectl
+	retry 5 sudo apt-get -qq -y install \
+		kubectl=${kubernetes_release}-00 \
+		kubelet=${kubernetes_release}-00
+	sudo apt-mark hold kubelet kubectl
+	retry 5 sudo systemctl restart kubelet
 }
 
 if [ "${kubernetes_release}" \< "1.15" ]; then
@@ -204,7 +213,7 @@ if [ "${kubernetes_release}" \< "1.15" ]; then
 	sleep 2
 	exit 1
 fi
-if sudo kubeadm init phase preflight --config install/kubeadm.conf 2>&1 | grep -q "ERROR Port-6443"
+if ss -lnt | grep -q :6443
 then
         upgrade
 else
diff --git a/worker/templates/upgrade-worker b/worker/templates/upgrade-worker
--- a/worker/templates/upgrade-worker
+++ b/worker/templates/upgrade-worker
@@ -1,7 +1,83 @@
 #!/bin/bash
 
+# Retries a command on failure.
+# $1 - the max number of attempts
+# $2... - the command to run
+retry() {
+    local max_attempts="$${1}"; shift
+    local attempt_num=1
+
+    until "$${@}"
+    do
+        if [ "$${attempt_num}" -eq "$${max_attempts}" ]
+        then
+            echo "Attempt $${attempt_num} failed and there are no more attempts l
+eft!"
+            return 1
+        else
+            echo "Attempt $${attempt_num} failed! Trying again in $${attempt_num}
+seconds..."
+            sleep $(( attempt_num=attempt_num + 1 ))
+        fi
+    done
+}
+
+ensure_docker_settings() {
+	if [ ! -f /etc/docker/daemon.json ]
+	then
+		echo "Writing Updated Docker Configuration"
+		cat <<EOF | sudo tee /etc/docker/daemon.json
+{
+  "log-driver": "json-file",
+  "live-restore": true,
+  "log-opts": {
+    "max-size": "100m"
+  },
+  "storage-driver": "overlay2"
+}
+EOF
+		sudo systemctl reload docker
+		sudo mkdir -p /etc/systemd/system/docker.service.d
+		sudo systemctl daemon-reload
+	fi
+}
+
 echo "Ensuring installation has completed"
 cloud-init status --wait >/dev/null
 
 echo "Checking for upgrades"
+if [ -f /var/run/docker.sock ]
+then
+	ensure_docker_settings
+fi
 
+sudo systemctl enable iscsid && sudo systemctl start iscsid
+sudo apt-get -qq update -y
+sudo apt-get -qq install -y debconf-utils lvm2
+echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
+echo "Upgrading kubeadm"
+sudo apt-mark unhold kubeadm
+if ! sudo apt-get -qq -y install kubeadm=${kubernetes_release}-00
+then
+	sudo apt-mark hold kubeadm
+	echo "Failed to install kubeadm at version ${kubernetes_release}-00"
+	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
+	exit 2
+fi
+sudo apt-mark hold kubeadm
+echo "Upgrading worker node"
+case ${kubernetes_release} in
+	1.1[567].*)
+		retry 5 sudo kubeadm upgrade node
+		;;
+	1.14.*)
+		retry 5 sudo kubeadm upgrade node config --kubelet-version=${kubernetes_release}
+		;;
+esac
+echo "Upgrading kubelet"
+sudo apt-mark unhold kubelet kubectl
+retry 5 sudo apt-get -qq -y install \
+	kubectl=${kubernetes_release}-00 \
+	kubelet=${kubernetes_release}-00
+sudo apt-mark hold kubelet kubectl
+retry 5 sudo systemctl restart kubelet
