Support 1.28
Update default version to 1.28.3
Update autoscaler, and cri-tools to follow
Update Calico to 3.26.3
Support the new repos, including the debian package number changes,
in a backward compatible fashion.

diff --git a/worker/templates/upgrade-worker b/worker/templates/upgrade-worker
--- a/worker/templates/upgrade-worker
+++ b/worker/templates/upgrade-worker
@@ -69,26 +69,34 @@ $${APT_GET} install debconf-utils lvm2 nfs-common
 echo "docker.io docker.io/restart select true" | sudo debconf-set-selections
 # Upgrade cri-tools before upgrading kubeadm to avoid CRI API incompatibility
 echo "Upgrading cri-tools"
-if ! retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install cri-tools="${critools_release}-00"
+if ! cri_rel=$(apt-cache madison "cri-tools" | grep -Po "(?<= )${critools_release}[^ ]*")
+then
+    cri_rel="${critools_release}"
+fi
+if ! retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install cri-tools="$${cri_rel}"
 then
 	sudo apt-mark hold cri-tools
-	echo "Failed to install cri-tools at version ${critools_release}-00"
+	echo "Failed to install cri-tools at version $${cri_rel}"
 	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show cri-tools)"
 	return 2
 fi
 sudo apt-mark hold cri-tools
 echo "Upgrading kubeadm"
-if ! retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install kubeadm="${kubernetes_release}-00"
+if ! kube_rel=$(apt-cache madison "kubeadm" | grep -Po "(?<= )${kubernetes_release}[^ ]*")
+then
+    kube_rel="${kubernetes_release}"
+fi
+if ! retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install kubeadm="$${kube_rel}"
 then
 	sudo apt-mark hold kubeadm
-	echo "Failed to install kubeadm at version ${kubernetes_release}-00"
+	echo "Failed to install kubeadm at version $${kube_rel}"
 	echo "Version installed is at $(dpkg-query --showformat='$${Version}' --show kubeadm)"
 	exit 2
 fi
 sudo apt-mark hold kubeadm
 echo "Upgrading worker node"
 case ${kubernetes_release} in
-    1.2[234567].*)
+    1.2[2345678].*)
 		retry 5 sudo kubeadm upgrade node
 		;;
     *)
@@ -98,8 +106,8 @@ case ${kubernetes_release} in
 esac
 echo "Upgrading kubelet"
 retry 5 $${APT_GET} --allow-change-held-packages --allow-downgrades install \
-	kubectl="${kubernetes_release}-00" \
-	kubelet="${kubernetes_release}-00" \
+	kubectl="$${kube_rel}" \
+	kubelet="$${kube_rel}" \
     containerd
 sudo apt-mark hold kubelet kubectl
 retry 5 sudo systemctl restart kubelet
